[versions]
kotlinTarget = "1.9.0" # Minimum supported Kotlin version for consumers of the library
kotlinToolchain = "2.2.0" # Actual version used by tooling within this project

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinToolchain" }
