name: Manually triggered playground

on:
  workflow_dispatch:

env:

  IMAGE_NAME: ttl.sh/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v5
        with:
          ref: add-arm64-architecture

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build JVM stuff
        run: ./gradlew build

      - name: Build Docker images for amd64 and arm64
        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # So if we split on '/' and take the 3rd value, we can get the release name.
        run: |
          NEW_VERSION=1h
          IMAGE=${IMAGE_NAME}:${NEW_VERSION}
          echo "Building new version ${NEW_VERSION} of $IMAGE"
          ./gradlew jib --image="${IMAGE}"
